### ISSUE TITLE
[BUG] Top panel navigation in fixed position needs fix

### ISSUE THREAD

**Issue by soee** [ovidiub13/KubuntuAdverticaLightChild#1]
On small screens:

If we scroll down the page and top panel goes to fixed position, than activated menu is rendered ~ 20px under bottom panel border. This happens because this menu (#menu-main) in absolute position has 'top' space set to 73px (through .skt-mob-menu class).

Either panel height has to be changed or top space of menu.

**Comment by ovidiub13** [comment]
More details please.

**Comment by madpipeline** [comment]
Fixed
