### ISSUE TITLE
[BUG] Main navigation on medium screens breaks to two lines

### ISSUE THREAD

**Issue by soee** [ovidiub13/KubuntuAdverticaLightChild#2]
On medium screens main menu items (links) needs smaller paddings. Atm. they have 20px left and right padding. We can also change columns sizes in header because we have smaller logo. So:

`#logo span4 => #logo span3`
`top-nav-menu span8 => top-nav-menu span9`

**Comment by madpipeline** [comment]
Please close bug 1 since you replied here.

**Comment by soee** [comment]
@ovidiub13 these are different bugs, has nothing to do to each other.
