### ISSUE TITLE
background images make my eyes bleed

### ISSUE THREAD

**Issue by ChALkeR** [ovidiub13/KubuntuAdverticaLightChild#7]
Compare 
http://kubwp.kubuntu.co.uk/wp-content/uploads/2015/04/featured-image-repeat-x.png (364KB)
and
http://oserv.org/bugs/kubuntu.org/featured-image-repeat-x.nonoise.png (448KB).
The latter is only 23% heavier.

If it's too large for you, you can take http://oserv.org/bugs/kubuntu.org/featured-image-repeat-x.nonoise.8bit.png (212KB), it's 42% smaller in byte size than your current image and still looks way better.

Both of those still have banding (the 8bit version has more visible banding), and that's fixable for the first image (featured-image-repeat-x.nonoise.png), but I have no free time right now to do that (fixing that involves building Qt 5.6). Still, both of those images are better than what you have now.

**Comment by ChALkeR** [comment]
![featured-image-repeat-x orig](https://cloud.githubusercontent.com/assets/291301/9682689/b4fbb490-5311-11e5-87d8-afec0071b2c2.png)
![featured-image-repeat-x nonoise](https://cloud.githubusercontent.com/assets/291301/9682690/b4fde242-5311-11e5-9c5f-ae833ad2f735.png)
![featured-image-repeat-x nonoise 8bit](https://cloud.githubusercontent.com/assets/291301/9682691/b4feb6cc-5311-11e5-82cb-ef9b449594ff.png)

**Comment by madpipeline** [comment]
Updated the image on all pages in the title section.
The banner on the homepage will be replaced with a new one with Kubuntu Wily.

If you have experience with this, please talk with Aaron Honeycutt (ahoneybun on IRC) about making one.
If you want to fix the current one, please talk to him as well for the sources.
